#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac


. /usr/share/initramfs-tools/hook-functions


force_load drbd

copy_exec /sbin/drbdadm
copy_exec /sbin/drbdmeta
copy_exec /sbin/drbdsetup
# 8.3 not needed.
copy_exec /lib/drbd/drbdsetup-84
copy_exec /lib/drbd/drbdadm-84

mkdir -p "${DESTDIR}/var/lib/drbd"
cp -af /var/lib/drbd/node_id "${DESTDIR}/var/lib/drbd/node_id"

exit 0

